version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - '5005:8000'
